# Generated by Django 3.2 on 2021-05-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.TextField(default='ln5TSk'),
        ),
    ]
