# Generated by Django 3.2 on 2021-05-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=900)),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'BESTSELLERS',
            },
        ),
        migrations.RenameField(
            model_name='book',
            old_name='average_rating',
            new_name='rating',
        ),
    ]
