# Generated by Django 3.2 on 2021-04-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210427_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn13',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='book',
            name='num_pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='text_reviews_count',
        ),
        migrations.AlterField(
            model_name='book',
            name='bookID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
