# Generated by Django 3.2 on 2021-05-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210508_0237'),
        ('books', '0003_remove_book_slug'),
    ]

    operations = [
    ]
