# Generated by Django 3.2 on 2021-04-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210427_1257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
