# Generated by Django 3.2 on 2021-05-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_merge_0002_auto_20210508_0237_0003_remove_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestbook',
            name='genre',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
