# Generated by Django 3.2 on 2021-05-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_bookreview_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booknookuser',
            table=None,
        ),
    ]
