# Generated by Django 3.2 on 2021-05-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_booknookuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknookuser',
            name='ID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookreview',
            name='ID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='booknookuser',
            table='BOOKNOOKUSER',
        ),
        migrations.AlterModelTable(
            name='bookreview',
            table='BOOKREVIEW',
        ),
    ]
