# Generated by Django 3.2 on 2021-05-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_booknookuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
