# Generated by Django 3.2 on 2021-05-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210507_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='review_content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
