# Generated by Django 3.2 on 2021-05-07 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210507_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.booknookuser'),
        ),
    ]
