# Generated by Django 3.2 on 2021-05-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_bookreview_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booknookuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='ID',
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='title',
            field=models.TextField(),
        ),
    ]
