# Generated by Django 3.2 on 2021-05-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_bookreview_author'),
        ('user', '0007_auto_20210508_0237'),
    ]

    operations = [
    ]
