# Generated by Django 3.2 on 2021-05-08 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_merge_20210508_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='id',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='review_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.booknookuser'),
        ),
    ]
